// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	model "InstagramMock-v2/model"

	mock "github.com/stretchr/testify/mock"

	service "InstagramMock-v2/service"

	testing "testing"
)

// IPostService is an autogenerated mock type for the IPostService type
type IPostService struct {
	mock.Mock
}

// Create provides a mock function with given fields: p
func (_m *IPostService) Create(p service.PostCreateDTO) (model.Post, error) {
	ret := _m.Called(p)

	var r0 model.Post
	if rf, ok := ret.Get(0).(func(service.PostCreateDTO) model.Post); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(model.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(service.PostCreateDTO) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: postID
func (_m *IPostService) Delete(postID uint64) error {
	ret := _m.Called(postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: postID
func (_m *IPostService) FindByID(postID uint64) (model.Post, error) {
	ret := _m.Called(postID)

	var r0 model.Post
	if rf, ok := ret.Get(0).(func(uint64) model.Post); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Get(0).(model.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShowAll provides a mock function with given fields:
func (_m *IPostService) ShowAll() ([]model.Post, error) {
	ret := _m.Called()

	var r0 []model.Post
	if rf, ok := ret.Get(0).(func() []model.Post); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: p
func (_m *IPostService) Update(p service.PostUpdateDTO) (model.Post, error) {
	ret := _m.Called(p)

	var r0 model.Post
	if rf, ok := ret.Get(0).(func(service.PostUpdateDTO) model.Post); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(model.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(service.PostUpdateDTO) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPostService creates a new instance of IPostService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPostService(t testing.TB) *IPostService {
	mock := &IPostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
